### ISSUE TITLE
只使用纯核显问题

### ISSUE THREAD

**Issue by wizzeng** [cheneyxx/Hackintosh-10400-B460M-MORTAR#1]
如果只是用核显来显示，不使用独立显卡，会不会出现无法打开 PS，视频播放无法使用硬件加速的问题呢

**Comment by cheneyxx** [comment]
不会 一切正常的哈 你那个问题参考：https://www.bilibili.com/video/BV1sK411n7sk

**Comment by cheneyxx** [comment]
> 如果只是用核显来显示，不使用独立显卡，会不会出现无法打开 PS，视频播放无法使用硬件加速的问题呢

不会 一切正常的哈 你那个问题参考：https://www.bilibili.com/video/BV1sK411n7sk

**Comment by wizzeng** [comment]
哈哈 我看过这个 可惜我试了直接黑屏掉
