### ISSUE TITLE
iMessage无法登陆

### ISSUE THREAD

**Issue by huzhimaye** [cheneyxx/Hackintosh-10400-B460M-MORTAR#10]
网卡是博通BCM94360CD，其他配置和作者相同。
尝试改过三码和en0都不太行
不知道各位有没有什么好的建议♥️

**Comment by cheneyxx** [comment]
https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial

**Comment by huzhimaye** [comment]
> https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial

感谢🙏，前面的操作都尝试过不行果然是黑号了，看到最后一段给客服打了电话立马就可以登了
