### ISSUE TITLE
大佬，配置和你的一样，但是我的显示器是2K，能进OC安装界面，在跑apple进度条的时候，跑到一半显示器就提示无信号接入，但主机还是在运行。

### ISSUE THREAD

**Issue by rainy8000** [cheneyxx/Hackintosh-10400-B460M-MORTAR#11]
如题，用DP和HDMI线都是同样的问题，是不是config需要改下？

**Comment by cheneyxx** [comment]
![image](https://user-images.githubusercontent.com/10344793/99548303-74e6b300-29f3-11eb-9c95-2fb82951fa15.png)

![image](https://user-images.githubusercontent.com/10344793/99548398-934cae80-29f3-11eb-8431-0bd880da978e.png)

上面设置下2k分辨率 这里设置01

**Comment by rainy8000** [comment]
谢谢指点哈，晚上我回去试试

**Comment by rainy8000** [comment]
![499D73FA-8AE1-416A-91CC-06C9C8B063B1](https://user-images.githubusercontent.com/57345224/99811931-c2dcf180-2b80-11eb-983b-f68ba76dfeaa.jpeg)
特来感谢大佬，成功驱动Wi-Fi等，唯一缺憾是睡眠唤醒会死机，不知道是不是通病：）

**Comment by cheneyxx** [comment]
用Hackintool进去修复电源 用dp线没问题

**Comment by rainy8000** [comment]
谢谢，暂时关掉睡眠得了
![Uploading D63D66A2-1F61-4BBF-A59A-A53B592CC4FA.jpeg…]()
