### ISSUE TITLE
用HDMI 4K输出感觉鼠标移动有掉帧的现象

### ISSUE THREAD

**Issue by licoba** [cheneyxx/Hackintosh-10400-B460M-MORTAR#12]
不知道楼主或者大家有没有？就感觉没有DP输出流畅了

**Comment by licoba** [comment]
[![](https://pic.downk.cc/item/5fb6af1db18d627113c46058.jpg)](https://pic.downk.cc/item/5fb6af1db18d627113c46058.jpg)

看了一下屏幕刷新好像只有30Hz，这个可以设置吗？

**Comment by cheneyxx** [comment]
换线 换显示器 解决100%问题

**Comment by licoba** [comment]
> 换线 换显示器 解决100%问题

😂😂😂显示器怕是换不了了，但是我的也是hdmi2.0的线和显示器接口啊，奇怪了
