### ISSUE TITLE
OC 0.6.3 引导进入页面之后是俄文，请问在windows上面怎么修改

### ISSUE THREAD

**Issue by mizhiming521** [cheneyxx/Hackintosh-10400-B460M-MORTAR#15]

**Comment by cheneyxx** [comment]
不知道 我这是0.6.4

**Comment by mizhiming521** [comment]
好的谢谢作者，还有一个问题，就是黑苹果无法使用PC耳麦的麦克风功能。请问这个是驱动问题吗？

**Comment by cheneyxx** [comment]
不清楚 没有设备可以测试

**Comment by mizhiming521** [comment]
已经测试了  这个EFI 介入麦克风设备之后不能使用，不知道那个驱动错误，作者给点建议。我尝试修改

**Comment by cheneyxx** [comment]
AppleALC.kext

**Comment by mizhiming521** [comment]
好的  我去尝试一下

**Comment by mizhiming521** [comment]
中文问题是因为EFI中的config.plist中修复语言改成zh即可。
声卡问题是驱动识别的alc1200a 在作者里面是1200.所以要改布局。
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
找到B460M 迫击炮可能有多种声卡，我的1200a 布局采用1.重启解决

**Comment by mizhiming521** [comment]
谢谢作者大神
