### ISSUE TITLE
休眠问题. 接上无线网卡蓝牙后自动唤醒

### ISSUE THREAD

**Issue by q447643445** [cheneyxx/Hackintosh-10400-B460M-MORTAR#16]
没装无线网卡前, 是可以完美休眠的. 淘宝上买了一个免驱的无线网卡蓝牙 .型号是 BCM94360CD 
插pcie接口上 蓝牙是额外一根线是接主板USB 针脚上. 
装上之后直接就能用.   但是!!发现 休眠有问题. 休眠 停机 几秒后又自动唤醒.  
找到原因 可能是因为蓝牙 usb定制问题.  因为这个efi是已经定制过了.  找了好多资料 实在不会如何在这个efi 上定制usb.
按照教程用Hackintool 找出蓝牙线的usb口  可是根本没识别出来,  可能这个定制过usb 的efi已经把那个 给删了.
不知道如何重新定制usb 或者还原usb接口数量

**Comment by cheneyxx** [comment]
USB定制用的是别人的 那个有点麻烦所以没有自己去折腾

**Comment by q447643445** [comment]
今天下班回家又开始弄这个问题了.  翻了一下远景论坛找到原因了. 现在B460m迫击炮 板子 无法内置usb蓝牙.  
只能关闭usb唤醒. 或者用前置usb3.0口转2.0口接蓝牙. 才可以解决装免驱白果 无线网卡蓝牙睡眠后秒唤醒的问题.
我选择关闭usb唤醒 用电源唤醒. 
参考链接:
[http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1876729&highlight=%C6%C8%BB%F7%C5%DA%2B%CB%AF%C3%DF](url)
[](url)

**Comment by cheneyxx** [comment]
其实我现在也关闭USB唤醒了 因为关机状态下按鼠标或键盘就能直接开机 关闭之后我就用开机键唤醒
