### ISSUE TITLE
11.1 麦克风不能使用

### ISSUE THREAD

**Issue by 81024198** [cheneyxx/Hackintosh-10400-B460M-MORTAR#17]
11.1 麦克风不能使用
音响正常使用

**Comment by cheneyxx** [comment]
声卡问题 驱动识别的可能是alc1200a 我的配置里是1200 所以要改布局
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
找到B460M 迫击炮可能有多种声卡 你的可能是1200a 布局采用1.重启解决

**Comment by 81024198** [comment]
> 声卡问题 驱动识别的可能是alc1200a 我的配置里是1200 所以要改布局
> https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
> 找到B460M 迫击炮可能有多种声卡 你的可能是1200a 布局采用1.重启解决

怎么操作这个？百度了半天没找到教程

**Comment by mizhiming521** [comment]
我也碰到这个问题，B460M主板声卡布局每各有所区别自己修改一下就行，采用hackintools 修改就行或者opencore-configture、pTree等等
