### ISSUE TITLE
10700是否集显是都可以上？？

### ISSUE THREAD

**Issue by UPMuling** [cheneyxx/Hackintosh-10400-B460M-MORTAR#21]
10700是否集显是都可以上？？

**Comment by cheneyxx** [comment]
没有测试环境 你可以试试

UPMuling <notifications@github.com>于2021年2月11日 周四13:40写道：

**Comment by UPMuling** [comment]
bios 设置是否需要按照images文件夹中图片配置吗？

**Comment by cheneyxx** [comment]
是的

UPMuling <notifications@github.com> 于2021年2月14日周日 下午5:00写道：
