### ISSUE TITLE
休眠问题

### ISSUE THREAD

**Issue by yongqilv** [cheneyxx/Hackintosh-10400-B460M-MORTAR#22]
您好，我也使用了你的efi文件，但是休眠唤醒后主机灯是亮的，黑屏无输出。usb端口定制时hackintool中usb芯片组显示300，名称为???，您有什么好的想法吗？

**Comment by cheneyxx** [comment]
用Hackintool修复一下电源管理那里试试 我这边可以用电源键正常唤醒 usb端口定制用的别人的

yongqilv <notifications@github.com> 于2021年2月23日周二 下午11:25写道：
