### ISSUE TITLE
图形界面缩放卡顿的问题

### ISSUE THREAD

**Issue by P8CM** [cheneyxx/Hackintosh-10400-B460M-MORTAR#25]
请问图形界面缩放卡顿的问题要怎么解决？

例如：finder 里按空格预览文件卡顿在缩放的过程中，或者其他的一些有缩放效果的操作都会卡顿。

**Comment by cheneyxx** [comment]
卡顿我觉得是因为没有独立显卡 uhd630核显带4k显示器吃力
