### ISSUE TITLE
网卡驱动问题

### ISSUE THREAD

**Issue by Sincenir** [cheneyxx/Hackintosh-10400-B460M-MORTAR#26]
请问您那里使用了有线网卡吗?
我这里没有安装免驱的无线网卡, 使用有线网卡, 网卡驱动是安装完成的, 但是在系统里显示 **网络线缆已拔出**

**Comment by cheneyxx** [comment]
![image](https://user-images.githubusercontent.com/10344793/109586376-0fe94000-7b40-11eb-8d90-66917c11d2b5.png)

需要这样设置

**Comment by Sincenir** [comment]
大佬有时间可以加载image里, 感谢大佬, 大佬yes, 昨儿整一晚上换了好多驱动也没成功,
另外这套 efi 可以用在 10400f上,
我这里的配置是
10400f + 微星迫击炮
16g单条雷赤(长鑫颗粒)内存
凯侠rc10 500G 固态

**Comment by cheneyxx** [comment]
只要是这个主板的网卡都要这样设置才有网络
