### ISSUE TITLE
「板载Realtek RTL8125B千兆网卡」在哪里购买呀

### ISSUE THREAD

**Issue by licoba** [cheneyxx/Hackintosh-10400-B460M-MORTAR#3]
如题，找了淘宝和京东，好像没几个商品，想问下楼主在哪里买的

😊能上购买链接的话是最好的了

准备抄作业

**Comment by licoba** [comment]
还有很多人买的「BCM94360CD」这个型号的，淘宝倒是看到有很多在卖

**Comment by cheneyxx** [comment]
主板自带。。

**Comment by cheneyxx** [comment]
> 还有很多人买的「BCM94360CD」这个型号的，淘宝倒是看到有很多在卖

主板自带

**Comment by licoba** [comment]
> > 还有很多人买的「BCM94360CD」这个型号的，淘宝倒是看到有很多在卖
> 
> 主板自带
😁 那不用买无线网卡了对吗

**Comment by licoba** [comment]
但是我怎么记得，B460M这款主板是不带无线网卡的啊

**Comment by licoba** [comment]
明白了，配置清单里面的迫击炮，是不是Wi-Fi版本的？
![](https://pic.downk.cc/item/5fa8e2cb1cd1bbb86b71a122.jpg)

**Comment by cheneyxx** [comment]
> 明白了，配置清单里面的迫击炮，是不是Wi-Fi版本的？
> ![](https://camo.githubusercontent.com/9218572d1f36a24539abefbc9b6bef2539402f041cd21f05488c37d67539a417/68747470733a2f2f7069632e646f776e6b2e63632f6974656d2f3566613865326362316364316262623836623731613132322e6a7067)

就是普通的迫击炮 非wifi版本

**Comment by cheneyxx** [comment]
> 明白了，配置清单里面的迫击炮，是不是Wi-Fi版本的？
> ![](https://camo.githubusercontent.com/9218572d1f36a24539abefbc9b6bef2539402f041cd21f05488c37d67539a417/68747470733a2f2f7069632e646f776e6b2e63632f6974656d2f3566613865326362316364316262623836623731613132322e6a7067)

因为我现在没有用iPhone 所以AirDrop对我来说没啥用 就没有买无线网卡 我用的有线
