### ISSUE TITLE
睡眠变关机问题

### ISSUE THREAD

**Issue by zhj-nbu** [cheneyxx/Hackintosh-10400-B460M-MORTAR#31]
![睡眠错误报告](https://user-images.githubusercontent.com/68038598/111237696-91f16280-8630-11eb-8d56-596edad75e61.jpg)
点睡眠的时候会变成关机（偶发）。主板和CPU都和你的一样。在电源管理日志里有一行：“SMC shutdown cause: 5: Software initiated shutdown ”
不知道咋回事

**Comment by cheneyxx** [comment]
从来没遇到过

zhj-nbu ***@***.***>于2021年3月16日 周二08:25写道：

**Comment by zhj-nbu** [comment]
谢谢回复。看来只能尽量不睡眠了

**Comment by zhj-nbu** [comment]
> 从来没遇到过 zhj-nbu ***@***.***>于2021年3月16日 周二08:25写道：
> […](#)

忘记咨询下，需要再进行USB定制吗？USB定制说可以解决睡眠问题

**Comment by cheneyxx** [comment]
没有时间去折腾了 我用着没问题 你如果发现哪个的usb定制驱动好用跟我说一下 我看看

zhj-nbu ***@***.***> 于2021年3月16日周二 上午11:26写道：
