### ISSUE TITLE
11.2.3显示有点问题，有时会黑屏二秒，有时一条线出现

### ISSUE THREAD

**Issue by vip212** [cheneyxx/Hackintosh-10400-B460M-MORTAR#34]
11.2.3显示有点问题，有时会黑屏二秒，有时一条线出现
麻烦大神更新下

**Comment by cheneyxx** [comment]
我也是11.2.3 没有显示问题

**Comment by vip212** [comment]
那就奇怪了，我的是核显，24寸显示器！DP接口

**Comment by cheneyxx** [comment]
我核显 4k27寸没问题

vip212 ***@***.***>于2021年4月2日 周五17:13写道：

**Comment by vip212** [comment]
能更新一下吗，大神

**Comment by vip212** [comment]
已知晓问题了，是24寸的显示器不能用DP线的，用回hdmi线就解决了！
