### ISSUE TITLE
wifi版本蓝牙不可用

### ISSUE THREAD

**Issue by missyouneed1** [cheneyxx/Hackintosh-10400-B460M-MORTAR#35]
![QQ20210523-105934](https://user-images.githubusercontent.com/33920416/119246671-68cde080-bb51-11eb-932e-4d10efb09ab6.png)
他是这样子的 我尝试了usb重新定制，但是不行 参考以前有用户的回复操作 也不行 求解答

**Comment by cheneyxx** [comment]
我和你主板不一样 建议你去远景发帖咨询 或者屏蔽板载wifi 买个黑苹果的无线网卡来用

**Comment by alfchao** [comment]
我买了免驱的，换上可以直接用。
