### ISSUE TITLE
成功吃上！特来感谢大佬

### ISSUE THREAD

**Issue by licoba** [cheneyxx/Hackintosh-10400-B460M-MORTAR#4]
用这个EFI，照着楼主的硬件配置抄作业，成功吃上黑果了，安装过程几乎没有出什么幺蛾子，再次感谢😁

只是安装之前要注意一些东西：
1、bios主板里的安全启动等一些设置项要关，可以参考这个视频 https://www.bilibili.com/video/BV1w54y1i7Qr
2、我是双硬盘，可以参考这个视频进行双硬盘双系统安装 https://www.bilibili.com/video/BV1Bs411g7Gz （PS：抹盘的时候如果是固态应该选择APFS格式）

![](https://app.yinxiang.com/files/common-services/binary-datas/c2VydmljZVR5cGU9MiZzZXJ2aWNlRGF0YT17Im5vdGVHdWlkIjoiMDMxMmVkNzEtNjFmNS00Yzc1LTljNzctM2RiMGZmZGViNjEzIiwicmVzb3VyY0d1aWQiOiI0ZDE0OWUxOC0xMmI5LTRlY2ItYmMzMS04MGM0ZWEzZTlkMjkifQ==)

安装完成后好像有些问题：
1、声音不能调节，只能静音或者最大音量
2、有线网在睡眠之后会出现未连接的情况，需要在网卡里面再次设置一遍才行

另外还有一些问题想请教一下：
1、OC的引导怎么做美化呀？想要做一个带图标的引导
2、系统可以直接在设置里面进行升级吗？看到升级的图标老是想点

**Comment by cheneyxx** [comment]
> 用这个EFI，照着楼主的硬件配置抄作业，成功吃上黑果了，安装过程几乎没有出什么幺蛾子，再次感谢😁
> 
> 只是安装之前要注意一些东西：
> 1、bios主板里的安全启动等一些设置项要关，可以参考这个视频 https://www.bilibili.com/video/BV1w54y1i7Qr
> 2、我是双硬盘，可以参考这个视频进行双硬盘双系统安装 https://www.bilibili.com/video/BV1Bs411g7Gz （PS：抹盘的时候如果是固态应该选择APFS格式）
> 
> ![](https://camo.githubusercontent.com/e4a943c25cca5353b20739101e738982c4a9c75b4d8a4728253a41aea0adb027/68747470733a2f2f6170702e79696e7869616e672e636f6d2f66696c65732f636f6d6d6f6e2d73657276696365732f62696e6172792d64617461732f63325679646d6c6a5a565235634755394d695a7a5a584a3261574e6c5247463059543137496d35766447564864576c6b496a6f694d444d784d6d566b4e7a45744e6a466d4e533030597a63314c546c6a4e7a63744d3252694d475a6d5a4756694e6a457a49697769636d567a6233567959306431615751694f6949305a4445304f5755784f4330784d6d49354c54526c59324974596d4d7a4d5330344d474d305a57457a5a546c6b4d6a6b6966513d3d)
> 
> 安装完成后好像有些问题：
> 1、声音不能调节，只能静音或者最大音量
> 2、有线网在睡眠之后会出现未连接的情况，需要在网卡里面再次设置一遍才行
> 
> 另外还有一些问题想请教一下：
> 1、OC的引导怎么做美化呀？想要做一个带图标的引导
> 2、系统可以直接在设置里面进行升级吗？看到升级的图标老是想点

昨晚优化了一下 精简了核显补丁 DP和HDMI两个都支持 有两份配置 注意查看

**Comment by cheneyxx** [comment]
> 用这个EFI，照着楼主的硬件配置抄作业，成功吃上黑果了，安装过程几乎没有出什么幺蛾子，再次感谢😁
> 
> 只是安装之前要注意一些东西：
> 1、bios主板里的安全启动等一些设置项要关，可以参考这个视频 https://www.bilibili.com/video/BV1w54y1i7Qr
> 2、我是双硬盘，可以参考这个视频进行双硬盘双系统安装 https://www.bilibili.com/video/BV1Bs411g7Gz （PS：抹盘的时候如果是固态应该选择APFS格式）
> 
> ![](https://camo.githubusercontent.com/e4a943c25cca5353b20739101e738982c4a9c75b4d8a4728253a41aea0adb027/68747470733a2f2f6170702e79696e7869616e672e636f6d2f66696c65732f636f6d6d6f6e2d73657276696365732f62696e6172792d64617461732f63325679646d6c6a5a565235634755394d695a7a5a584a3261574e6c5247463059543137496d35766447564864576c6b496a6f694d444d784d6d566b4e7a45744e6a466d4e533030597a63314c546c6a4e7a63744d3252694d475a6d5a4756694e6a457a49697769636d567a6233567959306431615751694f6949305a4445304f5755784f4330784d6d49354c54526c59324974596d4d7a4d5330344d474d305a57457a5a546c6b4d6a6b6966513d3d)
> 
> 安装完成后好像有些问题：
> 1、声音不能调节，只能静音或者最大音量
> 2、有线网在睡眠之后会出现未连接的情况，需要在网卡里面再次设置一遍才行
> 
> 另外还有一些问题想请教一下：
> 1、OC的引导怎么做美化呀？想要做一个带图标的引导
> 2、系统可以直接在设置里面进行升级吗？看到升级的图标老是想点

1.声音可以调节啊 2.有线网我这里正常 目前基本没有bug

昨晚优化了一下 精简了核显补丁 DP和HDMI两个都支持 有两份配置 注意查看 美化引导可以网上自己看 也不难 可以升级 我安装了最新10.15.7安全更新

**Comment by cheneyxx** [comment]
![image](https://user-images.githubusercontent.com/10344793/98627377-14020f80-234f-11eb-8589-96f2ee09b915.png)

bios开启usb唤醒就行了 我测试过鼠标可以唤醒

**Comment by cheneyxx** [comment]
oc开机引导已经添加图标了

**Comment by licoba** [comment]
好的，我今天晚上回去再试试

**Comment by licoba** [comment]
引导主题OK了😁 声音调节是因为我显示器没有声音调节功能，目前我这里还有两个问题：
1、 晚上电脑进入睡眠，早上操作鼠标键盘只能亮灯，不能真正唤醒，需要按电源的开机键才能唤醒
2、主机的有线耳机接口，没有办法处处声音：插入耳机后，Mac系统不能识别到有线耳机，不能从headset输出

**Comment by cheneyxx** [comment]
1.bios打开唤醒事件里面的usb唤醒就行了 我目前更新了迫击炮最新bios也没问题 使用Hackintool软件查看电源那里是不是有红色的报错 是的话点修理功能修理一下
![image](https://user-images.githubusercontent.com/10344793/98762103-e03bee00-2411-11eb-9e5b-0ac723263396.png)
2.我用的小米3.5mm耳机 插机箱前置3.5mm耳机接口使用正常

**Comment by licoba** [comment]
那真是有点奇怪了，我回去再检查下

我连耳机都和你用的一样的👀

**Comment by licoba** [comment]
成功解决了，耳机没声音是因为机箱前面板  和主板之间的接线，松了😂
