### ISSUE TITLE
最新双输出文件版本DP文件成功，特来感谢,HDMI跑完进度条黑屏

### ISSUE THREAD

**Issue by gongzuo51** [cheneyxx/Hackintosh-10400-B460M-MORTAR#6]
最新双输出文件版本DP文件成功，特来感谢

**Comment by gongzuo51** [comment]
大家有没有升级的，是否支持11 ？

**Comment by cheneyxx** [comment]
你显示器是4k吗 有没有用独显 我这边测试正常 一开始就是用的hdmi

**Comment by niuxianghui** [comment]
我之前用这个也是在4k模式下黑屏。
后来就自己做引导了，但是会出现睡眠唤醒后重启一下显示器才行，不然会黑屏，你有遇到这种情况吗？> 最新双输出文件版本DP文件成功，特来感谢

**Comment by cheneyxx** [comment]
![image](https://user-images.githubusercontent.com/10344793/99039662-b1b14500-25c2-11eb-8e34-e57c2f36a266.png)

并不会黑屏

**Comment by licoba** [comment]
> 大家有没有升级的，是否支持11 ？

准备今晚或者明晚升级，我也在观望

**Comment by gongzuo51** [comment]
> 你显示器是4k吗 有没有用独显 我这边测试正常 一开始就是用的hdmi

有可能是我的线有问题？我换条线试试

**Comment by gongzuo51** [comment]
> > 大家有没有升级的，是否支持11 ？
> 
> 准备今晚或者明晚升级，我也在观望

升级完成反馈下哈，我也在等

**Comment by gongzuo51** [comment]
> 我之前用这个也是在4k模式下黑屏。
> 后来就自己做引导了，但是会出现睡眠唤醒后重启一下显示器才行，不然会黑屏，你有遇到这种情况吗？> 最新双输出文件版本DP文件成功，特来感谢

你这个应该是主板bios配置的问题

**Comment by licoba** [comment]
> > > 大家有没有升级的，是否支持11 ？
> > 
> > 
> > 准备今晚或者明晚升级，我也在观望
> 
> 升级完成反馈下哈，我也在等

吃上了，没出啥问题，一切正常

**Comment by gongzuo51** [comment]
> > > > 大家有没有升级的，是否支持11 ？
> > > 
> > > 
> > > 准备今晚或者明晚升级，我也在观望
> > 
> > 
> > 升级完成反馈下哈，我也在等
> 
> 吃上了，没出啥问题，一切正常

OK，我也升级试试，直升的吗

**Comment by licoba** [comment]
> > > > > 大家有没有升级的，是否支持11 ？
> > > > 
> > > > 
> > > > 准备今晚或者明晚升级，我也在观望
> > > 
> > > 
> > > 升级完成反馈下哈，我也在等
> > 
> > 
> > 吃上了，没出啥问题，一切正常
> 
> OK，我也升级试试，直升的吗

直升的，出去吃了个饭，回来就好了

**Comment by niuxianghui** [comment]
> > 我之前用这个也是在4k模式下黑屏。
> > 后来就自己做引导了，但是会出现睡眠唤醒后重启一下显示器才行，不然会黑屏，你有遇到这种情况吗？> 最新双输出文件版本DP文件成功，特来感谢
> 
> 你这个应该是主板bios配置的问题

请问可能是主板的哪些配置会导致这个现象，有没有建议的调整选项呢？十分感谢回复！

**Comment by gongzuo51** [comment]
直升，11成功，感谢作者

**Comment by huzhimaye** [comment]
> > > 我之前用这个也是在4k模式下黑屏。
> > > 后来就自己做引导了，但是会出现睡眠唤醒后重启一下显示器才行，不然会黑屏，你有遇到这种情况吗？> 最新双输出文件版本DP文件成功，特来感谢
> > 
> > 
> > 你这个应该是主板bios配置的问题
> 
> 请问可能是主板的哪些配置会导致这个现象，有没有建议的调整选项呢？十分感谢回复！

我也遇到了这个问题😢

**Comment by gongzuo51** [comment]
> > > > 我之前用这个也是在4k模式下黑屏。
> > > > 后来就自己做引导了，但是会出现睡眠唤醒后重启一下显示器才行，不然会黑屏，你有遇到这种情况吗？> 最新双输出文件版本DP文件成功，特来感谢
> > > 
> > > 
> > > 你这个应该是主板bios配置的问题
> > 
> > 
> > 请问可能是主板的哪些配置会导致这个现象，有没有建议的调整选项呢？十分感谢回复！
> 
> 我也遇到了这个问题😢

试一下吧主板的节能选项打开，休眠直接输出就断掉了，唤醒之后等于拔插线，不过最好还是换DP线

**Comment by cheneyxx** [comment]
空了我把bios设置发出来 线的话建议dp

**Comment by huzhimaye** [comment]
> 空了我把bios设置发出来 线的话建议dp
❤️。dp1.2
<img width="469" alt="Screen Shot 2020-11-20 at 11 57 06" src="https://user-images.githubusercontent.com/31032722/99756241-aa8cb880-2b27-11eb-8390-bd3f9920b1c3.png">

**Comment by gongzuo51** [comment]
> 空了我把bios设置发出来 线的话建议dp

感谢，话说，在11 的系统上你的动画不丢帧吗，我的在启动台内点开文件夹特别明显的丢帧

**Comment by cheneyxx** [comment]
没升级 OpenCore还停留在0.6.3 新版本出来了我再更新EFI

gongzuo51 <notifications@github.com> 于2020年11月20日周五 下午12:26写道：

**Comment by niuxianghui** [comment]
> > > > 我之前用这个也是在4k模式下黑屏。
> > > > 后来就自己做引导了，但是会出现睡眠唤醒后重启一下显示器才行，不然会黑屏，你有遇到这种情况吗？> 最新双输出文件版本DP文件成功，特来感谢
> > > 
> > > 
> > > 你这个应该是主板bios配置的问题
> > 
> > 
> > 请问可能是主板的哪些配置会导致这个现象，有没有建议的调整选项呢？十分感谢回复！
> 
> 我也遇到了这个问题😢

你的这个问题解决了吗？

**Comment by huzhimaye** [comment]
> 空了我把bios设置发出来 线的话建议dp

Hi，按照如图的bios设置后睡眠后依然需要重启显示器😢

另，升级opencore是否只需要替换三码？

**Comment by cheneyxx** [comment]
我的LG显示器睡眠正常 opencore升级需要替换你自己的

**Comment by cheneyxx** [comment]
你们说的睡眠唤醒不了 显示器要重启 估计是显示器问题 LG的不会 我电脑都不关机
