### ISSUE TITLE
显示器偶尔黑屏

### ISSUE THREAD

**Issue by licoba** [cheneyxx/Hackintosh-10400-B460M-MORTAR#8]
我的显示器隔一段时间，会偶尔黑屏一下，黑屏的时间大概两三秒的样子

有时候是半个小时一次，有时候是连着会出现2、3次，线材应该没问题，前几天刚买的

请问可能是什么原因啊？

**Comment by cheneyxx** [comment]
![image](https://user-images.githubusercontent.com/10344793/99142745-01f7d800-2693-11eb-8628-0d44cc5859fe.png)

4k显示器最好用dp1.4的线(虽然我hdmi也没问题)

**Comment by gongzuo51** [comment]
我用DP，原来也会偶尔闪过黑一下，换根高质量线就好了。

**Comment by licoba** [comment]
> 我用DP，原来也会偶尔闪过黑一下，换根高质量线就好了。

你换的是啥线，有链接不，我怕再换一根还是这样

**Comment by licoba** [comment]
> 我用DP，原来也会偶尔闪过黑一下，换根高质量线就好了。

等楼上答复呀，求推荐DP线

**Comment by gongzuo51** [comment]
> > 我用DP，原来也会偶尔闪过黑一下，换根高质量线就好了。
> 
> 等楼上答复呀，求推荐DP线

京东找支持4K的不闪屏的，贵的，自营的，随便一个就可以

**Comment by licoba** [comment]
> ![image](https://user-images.githubusercontent.com/10344793/99142745-01f7d800-2693-11eb-8628-0d44cc5859fe.png)
> 
> 4k显示器最好用dp1.4的线(虽然我hdmi也没问题)

请问用HDMI的线，需要设置什么东西吗？我的HDMI接口和线，但是只能开到30hz

**Comment by licoba** [comment]
我看了一下说明书，有写HDMI最大支持4096x2160 @30hz
是不是板载显卡的HDMI接口，就不支持4k 60hz输出啊？

**Comment by cheneyxx** [comment]
> > ![image](https://user-images.githubusercontent.com/10344793/99142745-01f7d800-2693-11eb-8628-0d44cc5859fe.png)
> > 4k显示器最好用dp1.4的线(虽然我hdmi也没问题)
> 
> 请问用HDMI的线，需要设置什么东西吗？我的HDMI接口和线，但是只能开到30hz

什么都不用设置 直接用 配置已经在EFI里面了

**Comment by licoba** [comment]
[![](https://pic.downk.cc/item/5fc655ebf81f7e3bd9898769.jpg)](https://pic.downk.cc/item/5fc655ebf81f7e3bd9898769.jpg)

是我理解的方式不对吗？

**Comment by licoba** [comment]
[![](https://pic.downk.cc/item/5fc65669f81f7e3bd989a67e.jpg)](https://pic.downk.cc/item/5fc65669f81f7e3bd989a67e.jpg)

[![](https://pic.downk.cc/item/5fc65675f81f7e3bd989a955.jpg)](https://pic.downk.cc/item/5fc65675f81f7e3bd989a955.jpg)

客服也说，不支持的

**Comment by cheneyxx** [comment]
换显示器换线 解决100%问题

**Comment by cheneyxx** [comment]
![image](https://user-images.githubusercontent.com/10344793/100767295-8fc61800-3434-11eb-8190-0a5656773200.png)

支持 支持 支持

换显示器换线 解决100%问题

**Comment by licoba** [comment]
> ![image](https://user-images.githubusercontent.com/10344793/100767295-8fc61800-3434-11eb-8190-0a5656773200.png)
> 
> 打了补丁肯定支持 不支持我干嘛要弄两份配置
> 
> 换显示器换线 解决100%问题

好！怎么打补丁？是更新UEFI吗

**Comment by gongzuo51** [comment]
我都有点看不下去了，作者本就是免费更新了给大家用的，如果大部分人用了都没问题，那你遇到问题是不是应该先百度一下，google一下，换各种方案试试，都解决不了再来问？
而且作者说得很清楚，换线，换线，换线~~~
你是不是应该换线试试，如果还有问题再来反馈？

**Comment by licoba** [comment]
> 我都有点看不下去了，作者本就是免费更新了给大家用的，如果大部分人用了都没问题，那你遇到问题是不是应该先百度一下，google一下，换各种方案试试，都解决不了再来问？
> 而且作者说得很清楚，换线，换线，换线~~~
> 你是不是应该换线试试，如果还有问题再来反馈？

闪屏这个issue问题是DP线的问题，可以跳过
确实应该再开一个issue，但是那个被关了，想了下问题也差不多，就写在了这里
现在我的疑问是：同一块主板核显，说明书上写着HDMI不支持60hz，但是根据你的描述，我理解的是：「大部分人」都可以用HDMI线开启60hz？那我就更加好奇了，到底是哪里出了问题，已经百度Google了，都解决不了，所以我来提问了

**Comment by cheneyxx** [comment]
> > 我都有点看不下去了，作者本就是免费更新了给大家用的，如果大部分人用了都没问题，那你遇到问题是不是应该先百度一下，google一下，换各种方案试试，都解决不了再来问？
> > 而且作者说得很清楚，换线，换线，换线~~~
> > 你是不是应该换线试试，如果还有问题再来反馈？
> 
> 闪屏这个issue问题是DP线的问题，可以跳过
> 确实应该再开一个issue，但是那个被关了，想了下问题也差不多，就写在了这里
> 现在我的疑问是：同一块主板核显，说明书上写着HDMI不支持60hz，但是根据你的描述，我理解的是：「大部分人」都可以用HDMI线开启60hz？那我就更加好奇了，到底是哪里出了问题，已经百度Google了，都解决不了，所以我来提问了

hdmi那个配置是打好了hdmi2.0补丁的 在我的lg显示器上直接就能用 60帧刷新率没问题 用起来跟dp是一样的 上次你反映我就去把线换了配置换了测试正常 为啥你线换了还不行 多半是你显示器问题嘛

**Comment by cheneyxx** [comment]
> > 我都有点看不下去了，作者本就是免费更新了给大家用的，如果大部分人用了都没问题，那你遇到问题是不是应该先百度一下，google一下，换各种方案试试，都解决不了再来问？
> > 而且作者说得很清楚，换线，换线，换线~~~
> > 你是不是应该换线试试，如果还有问题再来反馈？
> 
> 闪屏这个issue问题是DP线的问题，可以跳过
> 确实应该再开一个issue，但是那个被关了，想了下问题也差不多，就写在了这里
> 现在我的疑问是：同一块主板核显，说明书上写着HDMI不支持60hz，但是根据你的描述，我理解的是：「大部分人」都可以用HDMI线开启60hz？那我就更加好奇了，到底是哪里出了问题，已经百度Google了，都解决不了，所以我来提问了
> 线是HDMI2.0的，显示器接口是HDMI2.0的，换线只是解决闪屏的问题，不能解决连60hz选项都没有的问题
> 那既然README写了支持HDMI 4k60hz输出，这与我百度和Google得来的资料以及客服的资料相冲突，我就只能在这里提问

只能说在我的LG显示器上是没问题的 我没有其他显示器可以测试 所以你的问题我解决不了 你的显示器是不是不能用DP线？能用DP线就别去折腾HDMI 你参考这个能不能解决你的问题：https://www.bilibili.com/video/BV1sK411n7sk

**Comment by licoba** [comment]
> > > 我都有点看不下去了，作者本就是免费更新了给大家用的，如果大部分人用了都没问题，那你遇到问题是不是应该先百度一下，google一下，换各种方案试试，都解决不了再来问？
> > > 而且作者说得很清楚，换线，换线，换线~~~
> > > 你是不是应该换线试试，如果还有问题再来反馈？
> > 
> > 
> > 闪屏这个issue问题是DP线的问题，可以跳过
> > 确实应该再开一个issue，但是那个被关了，想了下问题也差不多，就写在了这里
> > 现在我的疑问是：同一块主板核显，说明书上写着HDMI不支持60hz，但是根据你的描述，我理解的是：「大部分人」都可以用HDMI线开启60hz？那我就更加好奇了，到底是哪里出了问题，已经百度Google了，都解决不了，所以我来提问了
> > 线是HDMI2.0的，显示器接口是HDMI2.0的，换线只是解决闪屏的问题，不能解决连60hz选项都没有的问题
> > 那既然README写了支持HDMI 4k60hz输出，这与我百度和Google得来的资料以及客服的资料相冲突，我就只能在这里提问
> 
> 只能说在我的LG显示器上是没问题的 我没有其他显示器可以测试 所以你的问题我解决不了 你的显示器是不是不能用DP线？能用DP线就别去折腾HDMI 你参考这个能不能解决你的问题：https://www.bilibili.com/video/BV1sK411n7sk

好的，换DP线解决了，提问关闭了，感谢两位
